defaults:
  - base

name: "mytask"
description: "Pi0.5 libero_10 task 7"
type: simulation  # or "real_world"

environment:
  name: "libero_10"   # gym env ID or custom name
  ts: 0.1                  # timestep
  max_episode_steps: 600
  fail_on_error: true
  fail_after_steps: 600

observation_space:
  observation_type: "rgb"
  observation_shape: ${task.observation_space.rgb.shape}
  rgb:
    format: "(H,W,C)"
    shape: (360, 360, 3)   # your camera resolution
  observation_dim: 2048    # embedding dim from your model

state_space:
  state_dim: 34            # your robot's state vector size

action_space:
  action_type: "continuous"
  actions:
    dim: 7                 # your action dimensions
    action_bounds:
    action_mapping:
      position: [0, 1, 2]
      rotation: [3, 4, 5]
      gripper: [6]
  action_pred:
    format: "(batch_size, prediction_horizon, action_dim)"
    action_prediction_horizon: 50   # your model's horizon
    batch_size: 256
    shape: (${task.action_space.action_pred.batch_size}, ${task.action_space.action_pred.action_prediction_horizon}, ${task.action_space.actions.dim})
  action_execution_horizon: 8